# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-20 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
         migrations.CreateModel(
            name='Description_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2050)),
                ('video_uri', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sub', models.CharField(max_length=150)),
            ],
        ),
        
        migrations.CreateModel(
            name='Section_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('sub_title', models.ManyToManyField(to='Learning.Chapter_details')),
            ],
        ),
        migrations.AddField(
            model_name='chapter_details',
            name='details',
            field=models.ManyToManyField(to='Learning.Description_details'),
        ),
    ]
