# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0002_section_details_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='section_details',
            name='slide_image',
            field=models.ManyToManyField(to='Learning.SlideImages'),
        ),
    ]
