# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-20 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0003_auto_20221220_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_details',
            name='slide_image',
        ),
    ]
