# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0004_remove_section_details_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimages',
            name='game_type',
            field=models.PositiveIntegerField(choices=[(1, 'Cricket'), (2, 'Footbal')], default=1),
        ),
    ]
