# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-21 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0006_auto_20221221_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_details',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Learning.Games_Type'),
        ),
    ]
