# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-21 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0007_auto_20221221_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
